### ISSUE TITLE
What is the arg vocab_file?

### ISSUE THREAD

**Issue by memray** [king-menin/yttm_transformers_tokenizer#1]
Hi,

Thank you for implementing this YTTM API for HF transformer. I wonder what is the vocab_file in your example. Can you give an example of loading the vocab from a HF pretrained model? 

I download a RoBERTa [vocab](https://s3.amazonaws.com/models.huggingface.co/bert/roberta-base-vocab.json) from HF and try loading it with `tokenizer = YTTMTransformersTokenizer.from_pretrained(vocab_file=my_vocab_path)` but it reports the error:
`terminate called after throwing an instance of 'std::out_of_range'
  what():  Argument passed to at() was not in the map.`

Thank you,
Rui

**Comment by king-menin** [comment]
It is class for using https://github.com/VKCOM/YouTokenToMe tokenizer in HF transformers. Not for already pretrained models  in HF transformers. You should train your own tokenizer with YouTokenToMe and load with this class.

**Comment by memray** [comment]
Thanks! I guess it would be cooler if it can load pre-trained vocabs directly.
